#!/usr/bin/env node
if(process.argv[2] == "schema" && process.argv[3] !== undefined) {
    var app = require('./typson-schema.js');
    app.exec(process.argv[3]);
} else {
    require('sys').print('Usage: typson schema <url-or-path-to-type-script-file>\n');
}
